name: auto_load_api
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  cupertino_icons: ^0.1.2
  built_value: ^6.7.1
  built_collection: ^4.2.2
  flutter_youtube: ^1.1.6
  url_launcher: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  built_value_generator: ^6.7.1
  build_runner: ^1.6.7

flutter:
  uses-material-design: true